server:
  port: 8081

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

spring:
  application:
    name: user-service
  datasource:
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/microserviceUser?createDatabaseIfNotExist=true